### PR TITLE
R16B crypto issue fixed

### PR DESCRIPTION
**Pull request by shizzard**
I've coded the small fix of the crypto library issue that is coming up when trying to compile the emysql under the R16B release. This fix is tested live.

### CODE REVIEW

**Comment by choptastic** [comment]
This works for recent releases of Erlang, but crypto:hash is a relatively recent addition, and is not backwards compatible with versions of Erlang prior to R15B02 or R15B01 (I forget which off the top of my head).

**Comment by shizzard** [comment]
Yeah, that's true. It will be fine to get just a parallel version of emysql that is compatible with R16B.

**Comment by choptastic** [comment]
An alternative solution could involve a rebar compile pre_hook that checks the capabilities of the installed Erlang versions and generates an include file that uses the most up-to-date variation.  For reference, I very recently did this for Nitrogen, and the pertinent commit can be found here: https://github.com/nitrogen/nitrogen_core/commit/d0aa7d7f3f8dd550c69265f8e87ce195e457bb6e

**Comment by shizzard** [comment]
Nice one :)

**Comment by choptastic** [comment]
I'd be happy to put together a PR based on those changes later today, unless you want to.

**Comment by choptastic** [comment]
I'll have a PR ready for this momentarily.

**Comment by jlouis** [comment]
I have been quite slow at merging stuff, but Jesse's patch is now in.

**Pull request closed without merging**
