### PR TITLE
Update src/emysql_util.erl

### PR DESCRIPTION
**Pull request by valinurovam**
Return value should be binary

### CODE REVIEW

**Comment by valinurovam** [comment]
Return value on this code section

encode(Val, binary, _) when is_float(Val) ->
    [Res] = io_lib:format("~w", [Val]),
    Res;

should be binary, not list.

**Comment by hdiedrich** [comment]
Hi Valinurov,

thanks for the request, looks very convincing, why would you add quote() though?

And, did you actually work with the change in a production environment or otherwise really battle tested it?

As I said it looks like a plain bug fix but this encoding part is just so fragile.

Thanks,
Henning

**Comment by valinurovam** [comment]
Hi, hdiedrich!

thanks for the response. Yes, I work with change in production.

**Comment by IvanYuilop** [comment]
This issue is _repeatable, annoying and easy to fix_. People keep opening issues, forking the project and making pull requests to fix it. The eonblast people have made changes to the project when the issue and its solution was well-know. But the issue is still there!. I wish more serious people made a fork of this library...

**Comment by jlouis** [comment]
Dupe of #57

**Comment by jlouis** [comment]
Fixed in #59, closing

**Pull request closed without merging**
