### PR TITLE
Improve performance when retrieving large blobs

### PR DESCRIPTION
**Pull request by waj**
This patch vastly improves the performance and memory usage while getting large blob results.
It makes a gen_tcp:recv call to retrieve the rest of the packet at once.

While testing this I found to decrease from 1.4 seconds to just 15ms to retrieve a blob of about 7Mb.

### CODE REVIEW

**Comment by jlouis** [comment]
The patch is nice. But what if I end up with a buffer where I have all of the packet directly? Then I get

```
true = PacketLength - byte_size(PacketData) =< 0
```

which will lead to errors. You will need some extra clauses to handle this case before I will take the patch. Or you will have to convince me that your reasoning is sound :) The problem I see is that you need to understand the case where you have access to all the data already.

The other thing to ponder is that you don't want to request Missing if the Missing-value is small. This will lead to you using the underlying TCP buffer in the kernel and this will be very slow. In that case, it is better to pull as much data as possible into Erlang and process it. A good guess for Missing is 1500 bytes.

**Comment by waj** [comment]
If the packet already have all the data then the first case of parse_buffer will match, so Missing is always strictly positive... am I correct? 

I agree with your comment about small buffers. I will make some profiling, do the change and send the pull request again.

**Comment by jlouis** [comment]
Oh, sorry, You are right! There is a case clause on top of it which matches if you have all data available, which I did not see. I'll definitely take this, especially if you make the change with small buffers :)

**Comment by waj** [comment]
I just tested and profiled this patch, with and without the special case for small buffers and I couldn't get any difference. I guess that gen_tcp still uses the buffer size (8k) as the smallest chunk and return portions of it or something like this.
I made many tests retrieving many thousand rows of different types but still cannot get a difference that makes me think one approach is better than the other. I'd say I like this patch just like it is because it's more simple.

**Comment by waj** [comment]
Ok I changed my mind... I still don't see a difference in the performance but less calls to gen_tcp:recv are performed when avoiding the small packets. I extracted the buffer size to a constant and use that as the threshold.

**Comment by jlouis** [comment]
Indeed. If you have many small rows, then the function call overhead quickly becomes quite high. But you need a lot of rows. The underlying buffer in the BEAM VM makes sure we don't have to pull data out of the socket at a slow rate however. But having all these calls is not going to help the speed.

I'll merge this later today I hope :)

**Pull request merged**
