### PR TITLE
add support for utf8mb4 encoding

### PR DESCRIPTION
**Pull request by taybin**
cherry-picked utf8mb4 commit onto master.

### CODE REVIEW

**Comment by taybin** [comment]
Taking over from https://github.com/Eonblast/Emysql/pull/37.

I didn't attempt a larger patch. This is just the individual patch you were interested in.

**Comment by taybin** [comment]
Is there still interest in merging this?

**Comment by jlouis** [comment]
It looks good to me and can probably be merged. On the grounds that having support, albeit perhaps slightly broken, is better than having no support at all.

**Comment by jlouis** [comment]
Okay, we are now discussing if there should be any encoding-stuff in the driver at all. I _think_ most of us are leaning toward a negative, but I am not entirely sure. The idea is that it is the user of the driver who knows what kind of encoding is best for him or her, so the only thing the driver should be doing is to believe in what the user sends and then let the database server respond back with an error if possible.

**Comment by hdiedrich** [comment]
Yes. I still wonder if moving encoding functionality into optional support functions makes any sense.

**Comment by jlouis** [comment]
If you need complex encoding support, then better provide another library that helps doing this. I have stripped the encoding support from the driver proper now and hence, this won't make it into the code base anymore.

**Pull request closed without merging**
