### PR TITLE
Add as_json output util #74

### PR DESCRIPTION
**Pull request by dorny**

### CODE REVIEW

**Comment by jlouis** [comment]
Yep, fix those and I think it may be worthwhile to have. Chances are that many people would want a way to convert a row into a JSON structure, since it is very common nowadays to present data as JSON. Since there is already several convenience operations in the mix, this one seems like a natural utility addition.

You may also want to add a little hint in README.md about the new utility call.

**Comment by jlouis** [comment]
Ping :)

**Comment by dorny** [comment]
I was quite busy last days, but this week (hope tomorrow) i will definitely work on this :)

**Comment by dorny** [comment]
I have fixed issues you have mentioned. Add basic test case, hint in README and pull your latest commits. It's ok now?

**Comment by jlouis** [comment]
Awesome! I'll take a peek later today and merge if good.

**Comment by dorny** [comment]
I have looked on as_proplist util, which was recently added.
There are guard tests if field_list or rows are undefined.
Should i also add those guards?

It's possible to get result_packet with undefined field_list or it would cause error somewhere earlier in emysql_tcp?

**Comment by jlouis** [comment]
I think that what we should aim for here is that an empty result set should return an empty result in whatever coding the user has picked. In JSON, this would mean an empty JSON structure, in a `dict` it is an empty dict and so on. This way, the user has a simple way to determine empty result sets and can do something about them.

I think we should try to have a test for this as well, but I'll be looking at this later I think. Getting partial support for `as_json` is more important in the sort term run.

**Comment by dorny** [comment]
If mysql return empty result set:
`#result_packet.rows = []` and `mysql_util:as_json(Result) = []`
`[]` is correct representation of empty JSON array, so i think this is ok.

**Comment by jlouis** [comment]
Hi, I pushed a variant rebased to master rather than this. The reason for this is I want to keep master merges away from the master branch. If things does not apply cleanly, I'd much rather solve the conflict.

Only conflict was some old unicode-handling from before we stripped encoding in the driver. This has been removed now.

**Pull request closed without merging**
