### PR TITLE
add support of utf8mb4 encoding

### PR DESCRIPTION
**Pull request by taybin**
utf8 only supports 3 bytes of character encoding. To support the full 4 bytes, you need to use utf8mb4.

### CODE REVIEW

**Comment by taybin** [comment]
Any interest in this?

**Comment by hdiedrich** [comment]
Yes, very nice. I see that a good part of the diffing lines are from the error logger you introduced.

Can you share your rational about it? No doubt the io:format is stone age but what is the benefit of your logger?

Without researching it further, what are the differences of the 4 byte unicode? Is it, horrors, also slower? Needing more memory as per default? Why did Erlang bother with 3 byte Unicode in the first place?

Thanks if you would like to share your knowledge on that.

Henning

**Comment by taybin** [comment]
# error_logger

It's not my logger. It's a standard erlang module. I run emysql inside an ejabberd server and error messages would not show up at all until I switched over to error_logger. After switching to error_logger, all emysql messages showed up in the standard logfile.

# utf8mb4

If you look at the patch, you'll see that we're still using erlang's utf8 for encoding binaries. This is because erlang's utf8 is fine. The issue is with adding support for mysql's utf8mb4 encoding. I don't know why they shipped a broken utf8 that only supports 3 bytes out of a 4 byte encoding, but they did. [Here is a rational for always using utf8mb4](http://mathiasbynens.be/notes/mysql-utf8mb4). Using utf8mb4 shouldn't be any slower. Since it's UTF-8, it only uses the fourth byte if it needs to.

**Comment by Eonblast** [comment]
Hi thanks for coming back on that.

Did you have actual need of any utf8mb4 character?

Are you always running Emysql with the logger activated? Would that not slow things down a lot?

Would you like to propose a pull request that is only featuring the utf8mb4 part?

Thanks!
Henning

**Comment by taybin** [comment]
I've left the emysql logs commented out when in production because they were very numerous. One advantage of using error_logger is you can choose the severity level of the message. But I'll be happy to send a patch without it.

I have users from around the world. I think it's rediculous to offer UTF8 support and then only provide a subset. Besides, how else can someone show ☃, ☔, or ☕?

**Comment by hdiedrich** [comment]
Cool, at this point I would very much appreciate to get your utf8mb4-only patch.

Error logger sounds like a good choice, but today I would like to keep diffs to other forks as small as possible.

I still haven't checked out how important 4-byte UTF might be. The funny symbols are nice but what's more convincing to me is the thought that back and forth conversion will yield wrong results or, I guess, might even produce wrong characters in a string that was valid before storing it? That's sufficiently bad.

**Comment by taybin** [comment]
Well, I don't think it's even about how common the 4th byte is. The issue is that there is an encoding in mysql that isn't usable with Emysql because it only knows how to encode latin1 and utf8 because the encoding atom is passed to encode() directly.

This would be an issue if I was using macroman or latin2 or greek or hebrew encodings as well.

Maybe a bigger/better patch would add support for those encodings as well.

**Comment by hdiedrich** [comment]
If you would like to give it a shot, please do so!

I may have made life overly complicated for myself back then but I wasted a good bit of time trying to fix/improve the encoding (and it is still buggy for it).

That's why I am probably content with implementing UTF-8 correctly. I would think greek or hebrew-only encodings will be replaced by UTF-8 over time.

**Comment by taybin** [comment]
Replacing this with: https://github.com/Eonblast/Emysql/pull/53

**Pull request closed without merging**
