### PR TITLE
This should fix problem with float parameters

### PR DESCRIPTION
**Pull request by JLarky**

### CODE REVIEW

**Comment by manpages** [comment]
:+1: 
@JLarky , on a side note — you can refer to an issue of a parent-project using #-notation: #47 
Github also parses references to issues in the commit messages.

**Comment by JLarky** [comment]
@manpages I wasn't sure it will work as I commited it to my repo, which doesn't have 47 issues :)

**Comment by manpages** [comment]
It should have.

**Comment by jlouis** [comment]
Dupe of #57 - wrong fix, and also no test case.

**Comment by jlouis** [comment]
Fixed in #59, closing this one here.

**Pull request closed without merging**
