### PR TITLE
using os:timestamp/0 since erlang:now/0 is deprecated

### PR DESCRIPTION
**Pull request by marcelog**
Hello,

This replaces the call to erlang:now/0 (now fully deprecated) with a call to os:timestamp/0.

Any thoughts?

Thanks in advance!

### CODE REVIEW

**Comment by jlouis** [comment]
I don't maintain this anymore, but you could use the new Erlang Time API instead and then provide a fallback for the new API for the older releases of Erlang. There is a hint in the bottom of this file:

http://www.erlang.org/doc/apps/erts/time_correction.html

for creating a time compatibility library. As always, you should make 100% sure that you can make the time change. Subtle bugs tend to crop up. Your change from `erlang:now()` to `os:timestamp()` will not do time correction for instance. So you need to make sure this is really what you want.

**Comment by marcelog** [comment]
Thanks @jlouis that is a good point. What I thought in this particular scenario, is that since this is only used to send a ping through the connection (here: https://github.com/Eonblast/Emysql/blob/master/src/emysql_conn.erl#L331) it wouldn't hurt as much as a delay caused by using `erlang:now/0` when waiting to compensate time differences.

I'll close this one anyway if this project is not mantained anymore.

Thank you!

Best Regards,

**Comment by jlouis** [comment]
Oh, I think it is maintained, but not by me, though.

Your analysis is important: we are only using the timestamp for a time-window/duration. This usually means we want to use `erlang:monotonic_time()` as it is not susceptible to time correction and warps. And then fall back on systems which doesn't handle this. Also note the need to a call to `erlang:convert_time_unit/3` to get the `native` time unit down to `seconds`.

With these things in place, you can also define the code to be time-warp-safe, which means it can be used in systems where time may warp, without any worry.

**Comment by marcelog** [comment]
Got it. So if I understand your points correctly, the patch should really be something like:

``` erlang
now_seconds() ->
    try
        erlang:monotonic_time(seconds)
    catch
        error:undef ->
            {M, S, _} = erlang:now(),
            M * 1000000 + S
    end.
```

Makes sense?

**Comment by jlouis** [comment]
Yes, maybe use `erlang:now()` instead, and move it to a separate module so you can ask the compiler to ignore deprecation warnings.

**Comment by marcelog** [comment]
Yes, I replaced the call to `os:timestamp/0` with the original call to `erlang:now/0` in the last commit, it was a brain fart on my part :)

Thanks for your time @jlouis, this has been absolutely educational!

I can open a new pull request if desired.

Best!

**Pull request closed without merging**
