### PR TITLE
Fix a typespec error for Erlang 17 of dict() becoming dict:dict()

### PR DESCRIPTION
**Pull request by sebmaynard**

### CODE REVIEW

**Comment by saa** [comment]
This not working on erlang < 17.0

**Comment by sebmaynard** [comment]
You are quite right. I didn't realise that - I've just been testing exactly this and get "referring to built-in type dict as a remote type; please take out the module name" - under Erlang 17, without the dict:dict() it warnings (and again fails to build)

I'm not really sure what to do about this.

**Comment by jlouis** [comment]
Also note that Travis CI has found this immediately. I love having CI tests in this code. There was a resolution about this on the erlang mailing list, see

http://erlang.org/pipermail/erlang-questions/2014-March/078081.html

which is what we should be doing for Emysql until release 18.0 comes out. At that point we will deprecate support for R16 and downwards.

**Comment by sebmaynard** [comment]
@jlouis Which particularly, the local dict redefinition, or the nowarn_deprecated_type?

**Comment by jlouis** [comment]
I think we should go with nowarn_deprecated_type if it works in a backwards manner

**Comment by jlouis** [comment]
Looks good, did it kill the warning for Release 17.0 ?

**Comment by sebmaynard** [comment]
Sort of; unfortunately it blew up for a different set of types in another file, but only after I compiled it a second time (must have missed the first time); fixing  it now

**Comment by sebmaynard** [comment]
Maybe I should add the compile flag in the rebar.config, as there are types that cause problems in the include/emysql.hrl file. But then it won't compile properly <R17 without rebar.. thoughts?

**Comment by jlouis** [comment]
Adding the compile flag to rebar.config is indeed needed. And also to the Makefile structure if possible.

**Comment by jlouis** [comment]
Now 17.0 is out, could you recheck this?

**Comment by sebmaynard** [comment]
Seems to work just fine in 17.0. Hooray!

**Pull request merged**
