### PR TITLE
All records changed, requesting merge with master

### PR DESCRIPTION
**Pull request by emacstheviking**
Erlang best practice is to prefix all records with the name of the module to prevent clashes with other modules. I have applied this practice to all such records defined in "emysql.hrl" and built and used the project with no apparent side-effects.

Thanks for writing the module in the first place!

:)
Sean Charles.

### CODE REVIEW

**Comment by Eonblast** [comment]
Sorry Sean,

thank you for taking the time but you did not base it on the latest changes as I had explicitly warned you. You should have executed a pull before editing. As visible here [1] you are basically deleting the changes that have been added in the mean time.

[1] https://github.com/emacstheviking/Emysql/commit/b0b6bd2729b6afe756d081709e8e45167b75f5b1

Most is at the bottom.

Also, you are adding a lot of whitespace at the end of lines back in. I think that might also be because they had been cleaned up since the version that you based your work on. The whitespace can cause problems vor SVN, and some people check their Open modules in with their own sources to stay consistent.

Do you feel like fixing that? It should be easy to see if things work by using github's diff views. You should only see red lines, i.e. lines being dropped, that you are immediately replacing. Not as in [1].

Merry Christmas! and thanks for contributing,
Henning

**Comment by emacstheviking** [comment]
Being a long-0term SVN user us obviously not helping on github projects! LOL

I forked my github repository from eonblast, I assume that _was_ the 
latest... if you tell me what I have to do to ensure I get the latest 
version of the code then I can apply my changes... I will create patch 
files for what I did so far and then apply them to the latest version.

:)
Sean

**Comment by Eonblast** [comment]
Hi Sean!

After you forked, there were updates in the original. They don't automatically propagate into your fork obviously. I think there is no button for that at github. But locally, you would have to pull from the Eonblast repo BEFORE applying your changes. Or you can do some rebasing now to avoid doing it all over again, and in fact you might want to use this case to try to find out about rebase.

Rebase is a common thing in git although it sounds like a totally alien idea to SVN logic. So why not read up on it with this case as a guide. I found this post really helpful to get my head around it http://gitready.com/intermediate/2009/01/31/intro-to-rebase.html if I remember right. Or was it this: http://darwinweb.net/articles/the-case-for-git-rebase ? Here is more, from the source: http://book.git-scm.com/4_rebasing.html and finally the git doc itself will help: http://schacon.github.com/git/git-rebase.html

In my experience it helps reading them all first and then you'll still get lost in the beginning until it all becomes clearer. SVN thinking gets massively in the way of understanding git I found. Also, git is no super monolith at all. I can rarely understand what it does without understanding what actually happens underneath.

Cheers!
Henning

**Comment by Eonblast** [comment]
Cannot be merged w/o rebase and now rotten.

**Pull request closed without merging**
