### PR TITLE
improved version of mysql_util:as_records

### PR DESCRIPTION
**Pull request by ghost**
Here is improved version of function `mysql_util:as_records` in terms of `execution time` and `simplicity`. I have tests to prove it.

### CODE REVIEW

**Comment by jlouis** [comment]
Two questions: Do we have coverage of that part of the code? If yes, I'll take the patch. If no, I would ask if you could add a couple of tests to that part of the code so we get it covered.

As for your deletion of the generated documentation, I agree it should be deleted from the repository, but this is also for @hdiedrich to decide.

**Comment by ghost** [comment]
I wrote useful test.

**Comment by jlouis** [comment]
Thank you! And thank you for the cover configuration change.

**Comment by jlouis** [comment]
Thank you very much for this contribution!

**Pull request merged**
